version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ilovepdf-clone
    ports:
      - "8085:8085"
      - "8084:8084"
    environment:
      - PORT=8085
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - storage_data:/app/storage/uploads

volumes:
  storage_data:
