services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: omnipdf-app
    ports:
      - "8086:8084"
    environment:
      - PORT=8084
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - storage_data:/app/storage/uploads

volumes:
  storage_data:
